library(dplyr)
library(stringr)
library(ggplot2)
library(maps)
library(lubridate)
library(zoo)
library(ggmap)

level(service_new$wday)

###import data
service = read.csv("MyLA311_Service_Request_Data_2016.csv")

#tracking = read.csv("311_Call_Center_Tracking_Data.csv")
####change the first colname to Date
#colnames(tracking)[1] = "Date"

#### make a copy of service and tracking 
#tracking_cp = tracking
service_cp = service

####explore the dataset
###head(tracking,10)
###head(service,10)

#### date transformation
#tracking$Date=mdy(tracking$Date)
 
service$CreatedDate = mdy_hms(service$CreatedDate)
service$UpdatedDate = mdy_hms(service$UpdatedDate)
service$ClosedDate = mdy_hms(service$ClosedDate)
service$ServiceDate = mdy_hms(service$ServiceDate)
#mutate new date variables to service dataset
service$month = month(service$CreatedDate)
service$Year = year(service$CreatedDate)
service$yday = yday(service$ClosedDate)
service$ymd = ymd(str_sub(service$CreatedDate, start = 1 ,end = 10))
service$yearmon = as.yearmon(service$ymd , "%m %Y")
service$wday = wday(service$CreatedDate,label = T)

str(service$yearmon)

#### delete the NA row
#tracking_new <- tracking %>%
#                  filter(!is.na(Date))

# time range of each dataset
#unique(tracking_new$Date)  #2011-2015
#unique(service$Year) #2015-2016

###check whether there is duplated data in column:SRNumber
###result: 14 SRNumber is duplicated
#service %>%
#  filter(RequestType  =="Metal/Household Appliances")
#  Dup_SRN <- service %>%
#     group_by(SRNumber) %>%
#     summarise(cnt = n()) %>%
#     filter(cnt >1)

####14 Duplicated SRNumber
#1  1-159061711     2
#2  1-161044441     2
#3  1-161607751     2
#4  1-162058171     2
#5  1-163488451     2
#6  1-164172781     2
#7  1-168224741     2
#8  1-169242961     2
#9  1-169368491     2
#10 1-171348141     2
#11 1-181045901     2
#12 1-186887581     2
#13 1-186993766     2
#14 1-360912862     2

#Question:I¡¯m confused about what DriverSelfReport means. I assume this is not a request generated by the general public?
#Answere:	Yep. It¡¯s when a service tech in the field creates a report rather than somebody from the General Public. 

#remove the duplicated SRNumber
service_new <- service%>% filter(!(SRNumber %in% c("1-159061711","1-161044441","1-161607751","1-162058171","1-163488451","1-164172781","1-168224741","1-169242961","1-169368491","1-171348141","1-181045901","1-186887581","1-186993766","1-360912862")))

#tracking_mg=merge(tracking_new,service,by.x ='CreateDate',by.y = 'CreatedDate')  # return 0 cant not merge
#head(tracking_mg,10)
 
#1.1 Distribution of requests 


service_new %>%
  # filter(!is.na(seri$gender))%>%
  group_by(RequestType) %>%
  summarise(ReqType_cnt = n()) %>%
  
  ggplot(aes(x = reorder(RequestType,-ReqType_cnt), y = ReqType_cnt))+
  geom_bar(color = "white",stat = "identity",
           fill = c(rep("#f768a1",2),rep("#fbb4b9",10)))+
  scale_y_sqrt()+
  xlab("")+
  ylab("Sqrt Count") +
  ggtitle("RequestType Distribution")+
  
  theme(axis.title.x=element_text(size=18,face="bold",family="Times"),
        axis.title.y=element_text(size=18,face="bold",family="Times"),
        axis.text=element_text(family="Times",size=14),
        axis.text.x =  element_text(angle = 30, hjust = 1, size = 10), 
        legend.title=element_text(color="#3690c0",face="bold",size=16,family="Times"),
        legend.text=element_text(family="Times",size=12),
        plot.title=element_text(size=22,lineheight=0.8,
                                face="bold", 
                                margin=margin(10,0,10,0),
                                family = "Times"))

#1.2 Distribution of owner department (owner is who made it)

#BOE has only 2 records so delete it as there is no meaning comparted withe other owner
#service_new %>%
#   filter(Owner=="BOE")%>%
#  group_by(Owner) %>%
#  summarise(Owner_cnt = n()) 

service_new %>%
  filter(Owner !="BOE")%>%  # BOE has only 2 records so delete it as there is no meaning comparted withe other owner
  group_by(Owner) %>%
  summarise(Owner_cnt = n()) %>%
  ggplot(aes(x = reorder(Owner,-Owner_cnt), y = Owner_cnt))+
  geom_bar(fill  = "lightblue",color = "white",stat = "identity")+
  #scale_x_continuous(limits = c(0,1000),breaks = seq(0,1000,50))+
  scale_y_sqrt()+
  #scale_y_log10() +
  xlab("")+
  ylab("Sqrt Count") +
  ggtitle("Department Distribution")+
  theme(legend.position = "none")+
  theme(axis.title.x = element_text(color = "darkgrey", size = 16, face = "bold"),
        # axis.text.x = element_text(angle = 30, hjust = 1),
        axis.title.y = element_text(color = "darkgrey", size = 14, face = "bold"),
        plot.title = element_text(color = "darkgrey",size = 14, face = "bold"),
        legend.title = element_text(color = "darkgrey",size= 14),
        panel.background = element_rect(fill = "white")
  )   

# 2 input channel analysis
#2.1 Input channel comparision

service_new %>%
  #  group_by(RequestSource) %>%
  #  summarise(cnt = n())
  #  filter(RequestSource %in% c("Mobile App","Queue Initiated Customer Call","Call","Voicemail")) %>%
  group_by(RequestSource) %>%
  summarise(cnt = n()) %>%
  ggplot(aes(x = reorder(RequestSource,-cnt), y = cnt ))+
  geom_bar(color = "white",stat = "identity", position = "dodge",
           fill = c("#980043",rep("#dd1c77",4),rep("#df65b0",6),rep("#d7b5d8",6)))+
  #scale_x_continuous(limits = c(0,1000),breaks = seq(0,1000,50))+
  #scale_y_sqrt()+
  scale_y_log10() +
  xlab("")+
  ylab("Log Count") +
  ggtitle("RequestSource Distribution")+
  theme(axis.title.x=element_text(size=18,face="bold",family="Times"),
        axis.title.y=element_text(size=18,face="bold",family="Times"),
        axis.text=element_text(family="Times",size=14),
        axis.text.x =  element_text(angle = 30, hjust = 1, size = 10), 
        legend.title=element_text(color="#3690c0",face="bold",size=16,family="Times"),
        legend.text=element_text(family="Times",size=12),
        plot.title=element_text(size=22,lineheight=0.8,
                                face="bold", 
                                margin=margin(10,0,10,0),
                                family = "Times"))



qmap(location = "los angeles",color = "bw", zoom = 10, maptype = "roadmap") +
  stat_bin2d(data = service_new, aes( x = Longitude, y = Latitude, fill = RequestType) ,
             bins = 30, 
             alpha = 0.4)+
  facet_wrap(~RequestType)+
  ggtitle("RequestType Geo Bin Map")+
  theme(legend.position = "none")

qmap(location = "los angeles",color = "bw", zoom = 10, maptype = "roadmap") +
  stat_density2d(data = service_new, aes( x = Longitude, 
                                          y = Latitude,
                                          fill = ..level..), 
                 geom = "polygon") +
  scale_fill_gradient(low="white",high ="red")+
  facet_wrap(~RequestType) +
  ggtitle("RequestType Geo Density Map ")+
  theme(        plot.title=element_text(size=22,lineheight=0.8,
                                face="bold", 
                                margin=margin(10,0,10,0),
                                family = "Times"),
        legend.position = "none"
        )   

#2.2  App vs Phone call referrals, service type question for each input channel


service_new %>%
  filter(RequestSource %in% c("Call","Mobile App")) %>%
  group_by(RequestSource,RequestType) %>%
  summarise(cnt = n()) %>%
  ggplot(aes(x = reorder(RequestType,-cnt), y = cnt, fill = RequestSource))+
  geom_bar(color = "white",  stat = "identity", position = "dodge")+
  #scale_x_continuous(limits = c(0,1000),breaks = seq(0,1000,50))+
  scale_y_sqrt()+
  #  scale_y_log10() +
  # xlab("RequestType")+
  xlab("")+
  ylab("Sqrt Count") +
  xlab("")+
  ggtitle("RequestType Distribution")+
  scale_fill_manual(values = c("#addd8e","#31a354"))+
  
  
  
  theme(axis.title.x=element_text(size=18,face="bold",family="Times"),
        axis.title.y=element_text(size=18,face="bold",family="Times"),
        axis.text=element_text(family="Times",size=14),
        axis.text.x =  element_text(angle = 30, hjust = 1, size = 10), 
        legend.title=element_text(color="#3690c0",face="bold",size=16,family="Times"),
        legend.text=element_text(family="Times",size=12),
        legend.position = "none",
        plot.title=element_text(size=22,lineheight=0.8,
                                face="bold", 
                                margin=margin(10,0,10,0),
                                family = "Times"))

#3. Overall trends in calls/apps sums and counts


service_new %>%
  filter(RequestSource %in% c("Mobile App","Call") & RequestType %in% c("Bulky Items","Graffiti Removal")) %>%
  mutate(ReqTypeLevel = ifelse(RequestType =="Bulky Items","Bulky Items","Graffiti Removal")) %>%
  group_by(yearmon,RequestSource,ReqTypeLevel) %>%
  summarise(cnt = n()) %>%
  
  ggplot(aes(x = as.factor(yearmon), y = cnt, group = ReqTypeLevel, color = ReqTypeLevel )) +
  geom_jitter(alpha=0.5, position = position_jitter(h=0.7,w=0.4))+
  geom_smooth(method = "loess", se=F) +
  scale_color_manual(values = c("red","blue","black")) +
  xlab("") +
  ylab("Request Number")+
  ggtitle("Overall Trend of App and Call by Month")+
  facet_wrap(~RequestSource, ncol=1, scales = "free_y")+
  
  theme(axis.title.x=element_text(size=18,face="bold",family="Times"),
        axis.title.y=element_text(size=18,face="bold",family="Times"),
        axis.text=element_text(family="Times",size=14),
        axis.text.x =  element_text(angle = 30, hjust = 1, size = 10), 
        legend.title=element_text(color="#3690c0",face="bold",size=16,family="Times"),
        legend.text=element_text(family="Times",size=12),
        legend.position = "none",
        plot.title=element_text(size=22,lineheight=0.8,
                                face="bold", 
                                margin=margin(10,0,10,0),
                                family = "Times"))


# 4. %of calls handled vs referred.How much services we deliver over time.

#Status

#handled and referred
#meanless  

#service_new %>%
#  group_by(yearmon,Status) %>%
#  summarise(cnt = n()) %>%
#  #mutate(per = cnt/1090802.00 * 100 ) %>%
#  ggplot(aes(x = yearmon, y = cnt, fill = Status,order=desc(Status) )) +
#  geom_area(color = "black",size = .2,alpha = .5)+#alpha = 0.5, stat = "identity")+
# # scale_fill_brewer(palette="Blues")+
# # geom_smooth(method = "loess", se=F) +
# # scale_color_manual(values = c("pink","lightblue")) +
#  xlab("") +
#  ylab("Request Number")+
#  ggtitle("Servics Delivered Over Time")+
#  facet_grid(yearmon,Owner)+
#  theme(axis.title.x = element_text(color = "darkgrey", size = 16, face = "bold"),
#        axis.title.y = element_text(color = "darkgrey", size = 14, face = "bold"),
#        plot.title = element_text(color = "darkgrey",size = 14, face = "bold"),
#        legend.title = element_blank()
#        #legend.position = "none"
#        )   
	

# 5 Service type breakdowns. which requests are most common over time and areas.

 
service_new$ZipCode= as.character(service_new$ZipCode)

ziplonlat = service_new %>% 
    filter(str_detect(ZipCode,"[0-9]{5}") & !str_detect(ZipCode,"[A-Z]"))%>%
    group_by(ZipCode) %>% 
    summarise(cnt = n())

lon = geocode(ziplonlat$ZipCode)[1]
lat = geocode(ziplonlat$ZipCode)[2]
  
ziplonlat = cbind(ziplonlat,lon,lat)

topziplonlat <-ziplonlat %>% 
  arrange(-cnt)%>%
  slice(1:20)

LAmap <- qmap(location = "los angeles", zoom = 10, maptype = "roadmap") 

qmap(location = "los angeles", color = "bw", zoom = 10, maptype = "roadmap")  +
  geom_point(data = ziplonlat, aes(x =lon , y = lat,alpha = 0.4, size = cnt,col = cnt))+
  scale_color_continuous(low = "#fcc5c0", high = "red") +
  theme(legend.position = "none") +
  ggtitle("LA 311 Request Number by ZipCode")+
  
  theme(plot.title=element_text(size=22,lineheight=0.8,
                                face="bold", 
                                margin=margin(10,0,10,0),
                                family = "Times"),
        legend.title = element_blank(),
        legend.position = "none")


service_wday <- service_new %>%
  group_by(wday,Latitude,Longitude) %>%
  summarise(cnt = n())

lev=levels(service_wday$wday)
lev=lev[c(2,3,4,5,6,7,1)]
service_wday$wday = factor(service_wday$wday,level = lev)


qmap(location = "los angeles", color = "bw", zoom = 10, maptype = "roadmap")  +
  stat_density2d(data = service_wday, aes(x =Longitude , y = Latitude, fill = ..level..),
                 alpha = 0.4,
                 geom="polygon")+
  scale_fill_gradient(low = "white", high = "red") +
  ggtitle("LA 311 Request Number by Weekday")+
  facet_wrap(~wday,nrow = 2) +
  theme(plot.title=element_text(size=22,lineheight=0.8,
                                face="bold", 
                                margin=margin(10,0,10,0),
                                family = "Times"),
        legend.title = element_blank(),
        legend.position = "none")

#6.Illegal Dumping Pickup in CD and especially in CD8 and Wednesday
fcd <- read.csv("fcd.csv")

Dumping <- 
  service_new %>%
  filter(RequestType == "Illegal Dumping Pickup" & !is.na(CD)) %>%
  group_by(CD,Longitude,Latitude) %>%
  summarise(cnt = n())


#which CD has the most illegal dumping pickup request.


qmap(location = "los angeles", color = "bw", zoom = 10, maptype = "roadmap")  +
  stat_density2d(data = Dumping, aes(x =Longitude , y = Latitude, fill = ..level..),
                 alpha = 0.4,
                 geom="polygon")+
  scale_fill_gradient(low = "white", high = "darkred") +
  ggtitle("Illegal Dumping Pickup by CD")+
  
  # add Council Boundary Tier
  geom_polygon(data = fcd, aes(x = long, y = lat, group = group),fill = NA) +
  geom_path(data = fcd, aes(x = long, y = lat,group  = group), color = "black") +
  
  theme(
    legend.title=element_text(color="#3690c0",face="bold",size=16,family="Times"),
    
    legend.position = "none",
    plot.title=element_text(size=22,lineheight=0.8,
                            face="bold", 
                            margin=margin(10,0,10,0),
                            family = "Times"))



# 7.draw CD 8 wednesday illegal dumping pickup request map with zipcode boundary

zip <- read.csv("zip.csv")

CD8map <-  qmap(location = c(lat = 33.971725, lon = -118.289273), zoom = 13, maptype = "roadmap") 
CD8dump <- service_new %>% filter(RequestType == "Illegal Dumping Pickup" & CD =="8")

lev = levels(CD8dump$wday)
lev = lev[c(2,3,4,5,6,7,1)]
CD8dump$wday = factor(CD8dump$wday, levels = lev)

CD8map +
  stat_density2d(data = CD8dump, aes(x =Longitude , y = Latitude, fill = ..level..),
                 alpha = 0.4,
                 geom="polygon")+
  scale_fill_gradient(low = "white", high = "darkred") +
  #add zipcode boundary
  geom_polygon(data = zip, aes(x = long, y = lat, group = group), fill = NA) +
  geom_path(data = zip, aes(x = long, y = lat,group  = group), color = "darkgrey") +
  ggtitle("CD8 Illegal Dumping Pickup by Weekday") +
  facet_wrap(~wday, nrow = 2) +
  theme(legend.position = "none",
        plot.title=element_text(size=22,lineheight=0.8,
                                face="bold", 
                                margin=margin(10,0,10,0),
                                family = "Times"))

#9 Homeless Encampment

CD8efforts=read.csv("Possible_City-Owned_Sites_in_CD8_for_Homeless_Efforts.csv")

CD8homeless <- service_new %>%
                filter(RequestType == "Homeless Encampment" & CD == "8") 

CD8map <-  qmap(location = c(lat = 33.971725, lon = -118.289273), color = "bw", zoom = 13, maptype = "roadmap") 

CD8map +
  stat_density2d(data = CD8homeless, aes(x =Longitude , y = Latitude, fill = ..level..),
                 alpha = 0.4,
                 geom="polygon")+
  scale_fill_gradient(low = "#ffeda0", high = "#f03b20") +
  geom_point(data = CD8efforts , aes( x = lon, y = lat, size = sqrt(SquareFootage)),color = "#41ae76",alpha = 0.8)+
  #add zipcode boundary
  geom_polygon(data = zip, aes(x = long, y = lat, group = group), fill = NA) +
  geom_path(data = zip, aes(x = long, y = lat,group  = group), color = "darkgrey")+
  ggtitle("CD8 Possible Efforts for Homeless")
  theme(legend.title=element_text(color="#3690c0",face="bold",size=16,family="Times"),
        legend.position = "none",
        plot.title=element_text(size=22,lineheight=0.8,
                                face="bold", 
                                margin=margin(10,0,10,0),
                                family = "Times"))
#10 LED light replacement suggestion
fcd <- read.csv("fcd.csv")
LED=read.csv("Citywide_LED_Streetlight_Savings.csv")
colnames(LED)[8]="Savings"
LED$Fill= round(LED$Savings/100000,0)

light <- service_new %>%
  filter(!is.na(CD) &RequestType %in% c("Multiple Streetlight Issue","Single Streetlight Issue" ) ) %>%
  select(Latitude,Longitude,CD,RequestType)

lightmg <- merge(light, LED ,by.x = "CD", by.y = "Council.District",all.x = T)
fcdLED <-  merge(fcd, LED, by.x = "cd", by.y = "Council.District", all.x = T)

LAmap <-  qmap(location = "los angeles", color = "bw", zoom = 10, maptype = "roadmap") 


LAmap +
  #add councial district boundary
  geom_polygon(data = fcdLED, aes(x = long, y = lat, group = group, alpha = Fill),fill = "#3288bd")+
  #scale_fill_continuous(low = "white",high= "red")+
  geom_path(data = fcdLED, aes(x = long, y = lat,group  = group), color = "black")+
  #add street light issue
  stat_density2d(data = light, aes(x =Longitude , y = Latitude, fill = ..level..),
                 alpha = 0.4,
                 geom="polygon")+
  scale_fill_gradient(low = "#ffffbf", high = "#9e0142") +
  ggtitle("LED Streetlight Savings vs. Request") +
  theme(legend.title=element_text(color="#3690c0",face="bold",size=16,family="Times"),
        legend.position = "none",
        plot.title=element_text(size=22,lineheight=0.8,
                                face="bold", 
                                margin=margin(10,0,10,0),
                                family = "Times"))
  

LAmap +
  #add councial district boundary
  geom_polygon(data = fcdLED, aes(x = long, y = lat, group = group, alpha = Fill),fill = "#3288bd")+
  #scale_fill_continuous(low = "white",high= "red")+
  geom_path(data = fcdLED, aes(x = long, y = lat,group  = group), color = "black")+
  ggtitle("LED Streetlight Savings by CD")+
  theme(legend.title=element_text(color="#3690c0",face="bold",size=16,family="Times"),
        legend.position = "none",
        plot.title=element_text(size=22,lineheight=0.8,
                                face="bold", 
                                margin=margin(10,0,10,0),
                                family = "Times"))